Repository ICT2101-2201-P5-1/CoolMotor, pull requests merged in 2021-12, with the labels that each got.

#48 Testing/shawn
  Credentials/constants.py
  EditLevel.py.pdf
  Models/EditLevel.py
  test_EditLevel.py
Labels: Testing

#47 Testing/tudy
  Credentials/constants.py
  Models/EditLevel.py
  Models/displayLevel.py
  test_CoolMotor.py
  test_displayLevel.py
Labels: Testing

#49 Test/process file
  CoolMotor.py
  Levels/10.txt
  Levels/11.txt
  Levels/9.txt
  Models/processFile.py
  Models/processLogin.py
  static/img/chart1.png
  static/img/chart2.png
  test_processCommandsfile.txt
  test_processFile.py
  test_processGridfile.txt
  test_processLogin.py
Labels: Testing

#54 Hotfix remove distance variable
  CoolMotor.py
  static/img/chart1.png
  static/img/chart2.png
  static/js/game_processing.js
  templates/index.html
Labels: bug

#61 removed car testing page from nav bar. HOTFIX!!
  static/img/chart1.png
  static/img/chart2.png
  templates/base.html
Labels: enhancement
